default_context:
  project_name: 'storage-box-db-test'
  project_slug: 'storage-box-db-test'
  domain_main: 'photos.abrams.dk'
  domain_staging: 'stag.photos.abrams.dk'
  domain_base_api_url: 'http://photos.abrams.dk/api/v1'
  domain_base_ws_url: 'ws://photos.abrams.dk/api/v1'
  docker_swarm_stack_name_main: 'photos-abrams-dk'
  docker_swarm_stack_name_staging: 'stag-photos-abrams-dk'
  secret_key: 'changethis'
  first_superuser: 'admin@photos.abrams.dk'
  first_superuser_password: 'changethis'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.photos.abrams.dk", "https://stag.photos.abrams.dk", "https://photos.abrams.dk", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_tls: 'True'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@photos.abrams.dk'
  smtp_emails_from_name: 'Symona Adaro'
  smtp_emails_to_email: 'info@photos.abrams.dk'
  postgres_password: 'changethis'
  pgadmin_default_user: 'admin@photos.abrams.dk'
  pgadmin_default_user_password: 'changethis'
  neo4j_password: 'changethis'
  traefik_constraint_tag: 'photos.abrams.dk'
  traefik_constraint_tag_staging: 'stag.photos.abrams.dk'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:changethis'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/**/*.html, frontend/**/*.vue, frontend/.nuxt/*, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
